### ISSUE TITLE
Slice in populate throws error

### ISSUE THREAD

**Issue by donnanicolas** [LearnBoost/mongoose#1934]
I have two collection, a cart, and product
Cart has an array of items with references to products
The product has a prices array.

I want to do a query where I get the cart, and populate the products, but with the prices array sliced. I use the following query:

```
Cart.findById( id )
.populate({
	path:'items.products',
	options: {
		slice: {
			'prices': 1,
		}
	}
})
```

But it throws this error:

```
Error: slice() must be used after where() when called with these arguments
```

**Comment by tsabolov** [comment]
Any updates on this issue?

**Comment by vkarpov15** [comment]
Nope this issue got lost. Thanks for the poke.

General aside though, if you have to do a slice in a populate, [you may be using the "embedded array that grows without bound" antipattern](http://blog.mongolab.com/2013/04/thinking-about-arrays-in-mongodb/). With carts and products this probably isn't a problem though - I'm curious, why do you need to use slice?

**Comment by donnanicolas** [comment]
Sorry, I've changed the schemas, so I don't have this problem anymore, but just to put the example:

The products have an array of historical prices, but since it was getting huge, I only wanted the last price when getting the products, usually was not a problem, I slice them, but when getting the cart, I wanted to slice them in a populate it throw that error.

Now we save the historical prices in another collection.

**Comment by vkarpov15** [comment]
Yeah huge embedded arrays are typically a bad idea - they clog up bandwidth and they're unwieldy. However, the fact that slice is blowing up is a bit of an issue, will investigate.

**Comment by tsabolov** [comment]
I have a similar task: We have a collection of messages. Messages can have replies which are messages too. Only last reply (if any) should be returned with each message.
I've tried to make a population like this:
```js
query.populate({
  path: 'replies',
  options: {
    sort: { 'createdAt': -1 },
    limit: 1
  }
});
```
It works, but I've got another problem. I also need a total number of replies which is the `length` of `replies` array. I have a virtual property to get that. The thing is that after population `replies.length` becomes `1`.

**Comment by donnanicolas** [comment]
Thats a problem with your design not with mongoose. I'd recommend saving the length of replies in another field. This way you avoid the overhead of bringing all the replies, but still get the length of it.

That's the issue with NoSQL, you need to think things in a weird manner

**Comment by tsabolov** [comment]
@donnanicolas Thank you for your advice. I'll refactor my schema in such a way.

**Comment by vkarpov15** [comment]
@donnanicolas is right - mongodb is very fast with in-place update of integers, not as fast with adding new elements to an array. The general idea with mongodb is "store what you need to display" - if you need to display the number of messages that a user has, keep messages as a separate collection and have a counter in user for "number of messages" that you increment with $inc every time you save a new message.You can also do the same thing with tracking the last reply -  update a "last message" field with an update operation whenever you save a new message. Not entirely foolproof because mongodb doesn't have multi-document transactions, but if you're concerned about that you can use mongoose versioning to help :)

**Comment by donnanicolas** [comment]
Great, thanks!
