### ISSUE TITLE
mongoose 3.1.2

### ISSUE THREAD

**Issue by elkhawajah** [LearnBoost/mongoose#1961]
Hi,

I've been using mongoose#3.1.2 in production and recently I was refershing the node_modules when I got error that mongoose 3.1.2 does not exist https://registry.npmjs.org/mongoose/3.1.2 (this link does not return the info now )

Was it dropped by mistake ? When I tried to upgrade the version to 3.1.* I got two errors (I know these are not enough to debug the problem) but may be someone met these issues before

1. Cannot use $ne with Boolean
2. : RangeError: Maximum call stack size exceeded

I am using node.js 0.10.23

**Comment by nottinhill** [comment]
Confirming the problem is still there. http://stackoverflow.com/questions/24466366/mongoose-rangeerror-maximum-call-stack-size-exceeded

**Comment by vkarpov15** [comment]
Re: 3.1.2, I'm not quite sure why that's gone. That sounds like an npm issue though. If you want a quick workaround, [just pull the tarball from github in your package.json](https://github.com/LearnBoost/mongoose/archive/3.1.2.tar.gz). Either way, I would recommend upgrading to at least 3.8, 3.1 is not really going to be supported going forward.

Gonna take a look at the SO later today. In the meantime @nottinhill can you provide me a standalone script that repros the issue you're seeing?

**Comment by nottinhill** [comment]
Ok I created the different test cases (all on Mongoose 3.8.17).

https://gist.github.com/nottinhill/ce5aec815732e2a31cad

Explanation: Test-Case 1.1 and 1.2 fail, where I create an object the Mongoose-Model-way. Test-Case 2 works where I create the object the JSON way.

However: Maybe I have a mistake in my code: I am not sure about the nested `parsedFriend`object and if I need to create it too the Mongoose-Model-way.

Also maybe my Schema options like `.set('toJSON', {` are probably interferring. 

Maybe you have a clue.

**Comment by vkarpov15** [comment]
Case 1.1 will fail because of a stack overflow if you have sufficiently many docs. That's because, under the hood, mongoose 3.8.x uses `Function.prototype.apply()`, which pushes all the arguments onto the stack (see [this discussion re: why this happens in V8](https://code.google.com/p/v8/issues/detail?id=2896)). This isn't something I can fix in 3.8, but it is fixed in 4.0.0-rc2 - `Model.create()` will return an array if you pass it an array, and so not overflow the stack if the array is huge.

Case 1.2 will fail for reasons documented on the SO topic. Replace L33 with `docsArray.push(docs.toObject());` and it will work.

You can also use a module like async to do a bunch of `doc.save()` in parallel.

**Comment by nottinhill** [comment]
Confirmed working in 3.8, thanks Valerie, looking forward to Mongoose 4.0.

Now after applying `.toObject()* to my Mongoose Object, even with the native Node.js bulk insert, Dates and ObjectIDs are getting correctly created in MongoDB.

    date:    	{ type: Date, default: Date.now },
    userid:         '54340179407667e53192c92a',

converting correctly to:

    "userid" : ObjectId("54340179407667e53192c92a"),
    "date" : ISODate("2015-02-27T09:22:18.510Z")
