### ISSUE TITLE
Populating 2dsphere indexed fields

### ISSUE THREAD

**Issue by altitude** [LearnBoost/mongoose#2178]
I think it would be great to add populating examples to the documentation for 2dsphere indexed fields.

Experimenting with geo objects is tedious process, I'm probably missing something but I have not yet overcome casting or malformed geometry errors.

How can one successfully create a model with a geo polygon field ?

**Comment by vkarpov15** [comment]
So couple things:

1) Your schema can't include an array with two objects in it, because its unclear as to whether you mean "elements of this array can have either this schema or that schema" or "first element must have this schema and second element must have this other schema"

2) `type: [Array]` will bug out unfortunately. For now, you should just use `type: Array` and use a custom validator. Mongoose doesn't have very good support for nested arrays atm unfortunately.
