### ISSUE TITLE
Using String for _id locally, but ObjectId in Database

### ISSUE THREAD

**Issue by bendytree** [LearnBoost/mongoose#2352]
Is there a way to have `_id` be a string on the model, but an `ObjectId` in MongoDB?

Basically it's a bit painful to do equality with `ObjectId`, and I don't get much out of it being an `ObjectId` on my side. For example, finding a document in a collection:

##### Using ObjectId

    var match = _.find(documents, function(document){
      return String(document._id) === String(someId);
    }); 

##### Using String

    var match = _.find(documents, {_id:someId});

**Comment by vkarpov15** [comment]
Ah I see what you're getting at here. You're actually trying to compare ObjectId with its string equivalent. Unfortunately that won't quite work, but this is precisely what virtuals are for:

```
userSchema.virtual('id').get(function() {
  return this._id.toString();
});
```

You should then be able to use comparisons and lodash filters to your heart's content since `user1.id` and `user2.id` will just be strings.

**Comment by rkumar1904** [comment]
@bendytree You are correct !

**Comment by joaoreynolds** [comment]
For those looking for a solution here, I found wrapping the find function actually cleans my code up even more anyway:
```javascript
const _find = require('lodash/find')

module.exports = function findById(myArray, value, key = '_id'){
  return _find(myArray, myObj => String(myObj[key]) === String(value))
}
```
Use:
`const foundSubDocument = findById(document.subdocuments, '591e5e7a7bdf6f14accf11da')`

I also have a wrapper function for `_.findIndex` which looks almost the same.

**Comment by bendytree** [comment]
4 years later, I'll poke my head in again and say it'd still be nice if `_id` could be a string.

I'm sure `ObjectId`'s benefit some folks, but it's constant pain for me. I can count on one hand the number of times I've needed an actual `ObjectId` and would prefer calling the constructor in those scenarios.

Over and over I have to call `String(doc._id)` for comparisons or patch libs like `lodash` which isn't just ugly, but also very slow in tight loops. A string would work perfectly everywhere.

Totally recognize this is a mongodb thing and so maybe it's just impossible. Either way, mongoose is great and I really appreciate the library as-is.

**Comment by vkarpov15** [comment]
@bendytree I feel your pain. I'm hesitant to always convert objectids to strings because from the maintainer point of view it feels like too much magic.

We are working on a new feature for 5.4 that will give you this behavior with a one liner though: https://github.com/Automattic/mongoose/issues/6912

```
mongoose.ObjectId.get(v => v == null ? v : v.toString())
```

What are your thoughts on this syntax?

**Comment by bendytree** [comment]
Thanks @vkarpov15.  That would eliminate a lot of noise. Is that defined on each schema property? Would it work on lean objects?

Recasting to a string every time would have performance issues in a few tight spots.

If I'm honest, it feels like complexity breeding complexity whereas a plain string "just works".

But again, I totally get that this goes deep into mongo's core and definitely don't expect a fix here. Mainly I was hoping a few other heads would pop up in agreement, but it doesn't seem to be a common concern.

**Comment by vkarpov15** [comment]
@bendytree it would be on every schema property of type ObjectId, equivalent to setting a [custom getter](https://mongoosejs.com/docs/api.html#schematype_SchemaType-get) on every ObjectId path. It won't work with `lean()`, you'll still get an ObjectId.

If you want a plain string always without the headache, you can just store `_id` as a string. I agree this is a pain point, I have quite a bit of code in place for stripping out objectids so I can use chai's `.to.deep.equal()`. But the custom getter will eliminate that pain point, and I imagine the performance impact will be insignificant for most applications, especially if you're just using this for tests.

**Comment by jloveridge** [comment]
@bendytree I realize this was ages ago but why don't you just define your schema like:

```
const schema = new mongoose.Schema({
  _id: { type: String, default: () => (new mongoose.Types.ObjectId()).toHexString() },
});
```

**Comment by monteiz** [comment]
7 years later, I cannot find a way to have ObjectId automatically converted into its String representation.

I am trying with

`mongoose.ObjectId.get(v => v == null ? v : v.toString())`

as suggested by @vkarpov15 but with no avail.

I am using mongoose 8.18.1

Any idea? Because seriously, there is no point in having this ObjectId going around in the application, it has no benefits and only introduces a lot of bugs.

Having it as a string should be its default, ObjectId has no need to exist in a JavaScript application.

**Comment by vkarpov15** [comment]
@monteiz can you please provide an example of how you're using `mongoose.ObjectId.get()`? The following script shows that change makes `_id` a string:

```javascript
const mongoose = require('mongoose');

mongoose.ObjectId.get(v => v == null ? v : v.toString());

const schema = new mongoose.Schema({});
const TestModel = mongoose.model('Test', schema);

const doc = new TestModel();
console.log(typeof doc._id); // string
```
