### ISSUE TITLE
Mongoose queries hangs usings node.js domains

### ISSUE THREAD

**Issue by gabrielmoreira** [LearnBoost/mongoose#2464]
Why mongoose queries hangs after dispose domains, but insertions doesn't hangs?

My worker app, process each job with a new node.js domain. But mongoose stop working for next job when i dispose previous finished jobs.

Some isolated tests:

```javascript
var mongoose = require("mongoose");
mongoose.connect("mongodb://localhost:27017/sample");
mongoose.set('debug', true);

// Models
var SampleSchema = new mongoose.Schema({
	name: String,
});
var Sample = mongoose.model('Sample', SampleSchema);

// Create
function createUser(name, dispose) {
	var domain = require('domain').create();
	domain.run(function() {
		console.log("\n------------------------------\n");
		console.log("Creating user", name, (dispose ? "and dispose" : ""));
		var sample = new Sample();
		sample.name = name;
		sample.save(function(err) {
			console.log("User", name, "save", (err ? "error" : "OK"));
			if (dispose) {
				console.log("Domain disposed for", name);
				domain.dispose();
			}
		})
	});
}

// Retrieve
function retrieveUser(name, dispose) {
	var domain = require('domain').create();
	domain.run(function() {
		console.log("\n------------------------------\n");
		console.log("Retrieving user", name, (dispose ? "and dispose" : ""));
		Sample.findOne({name: name}, function(err, sample) {
			console.log("User", name, sample._id, "retrieved", (err ? "error" : "OK"));
			if (dispose) {
				console.log("Domain disposed for", name);
				domain.dispose();
			}
		});
	});
}


function test1() {
	setTimeout(  createUser.bind(this, "A", true),   0); // OK
	setTimeout(retrieveUser.bind(this, "A"      ), 100); // OK
}
function test2() {
	setTimeout(  createUser.bind(this, "A", true), 100); // OK
	setTimeout(retrieveUser.bind(this, "A"      ), 200); // PENDING QUERY!
}

function test3() {
	test1(); // OK
	setTimeout(retrieveUser.bind(this, "A"      ), 200); // OK
}
function test4() {
	test3(); // OK
	setTimeout(retrieveUser.bind(this, "A", true), 300); // OK
	setTimeout(retrieveUser.bind(this, "A"      ), 400); // PENDING QUERY!
}


function test5() {
	test2(); // PENDING QUERY!
	setTimeout(   createUser.bind(this, "B"     ), 300); // OK. Why?!?!?
}
function test6() {
	setTimeout(  createUser.bind(this, "C", true), 100); // OK. Why?!?!
	setTimeout(  createUser.bind(this, "D", true), 200); // OK. Why?!?!
	setTimeout(  createUser.bind(this, "E", true), 300); // OK. Why?!?!
	setTimeout(retrieveUser.bind(this, "C"      ), 400); // PENDING QUERY!
}


var testName = process.argv[2];
eval(testName + "()");

// exit process after 3 seconds
setTimeout(process.exit, process.argv[3] || 3000);
```

For a clean test, i run each test isolated, and drop collections after each test:
```shell
node test.js test1
node test.js test2
node test.js testN
```

**Comment by vkarpov15** [comment]
Yeah looks like there's something strange going on with timers and domains. If you just get rid of `utils.tick` in mquery, your tests seem to work (basically, mongoose's underlying query builder wraps callbacks in a `setImmediate()`). I'm just trying to figure out why this is happening. Either of y'all have any insights?

**Comment by vkarpov15** [comment]
Ok so long story short, as far as I can tell, this is a symptom of joyent/node#7136 where the domain stack doesn't get cleaned up properly: my current hypothesis is that node is refusing to run `setImmediate()` because there are disposed domains in the stack, but I don't know quite enough to be certain. The root problem is that node just flat out doesn't fire `setImmediate()` after the first dispose(), even though there are things in the immediateQueue. There are two workarounds:

1) Don't use `domain.dispose()`. Its been deprecated for 6 months now, and with good reason: it is broken. See joyent/node#5018 . Your test cases will work then.
2) Clean up the domain stack for node before calling dispose, which you should probably do anyway. As the above node issue showed, node sometimes pops the same domain onto the domain stack when you use setImmediate, etc., which mongoose does under the hood to ensure consistent async behavior.
```javascript
  var stack = domain._stack;
  var length = stack.length;
  while (--length >= 0 && stack[length] === d) {
    d.exit();
  }
  d.dispose();
```

Overall, I'd recommend against using domains though. As mentioned in joyent/node#7136, they're kinda the black sheep of nodejs error handling and tend to cause more problems than they solve. Plenty of alternatives: zones provide a similar API to domains, but without completely changing the behavior of the node core. Either way, IMO supporting long-deprecated behavior is more trouble than its worth.
