### ISSUE TITLE
Casts on Model.aggregate

### ISSUE THREAD

**Issue by mauriciogior** [LearnBoost/mongoose#2548]
Aggregation should cast ObjectId on `$match`.

I've tried this https://github.com/LearnBoost/mongoose/pull/2546#issuecomment-67352317, but it won't work as well stated by @vkarpov15

**Comment by DesignByOnyx** [comment]
One of the things that is nice about aggregation IMO is that it bypasses any of mongoose's auto-casting abstraction layer... making it very fast.  Not only is ObjectId not cast, but *none* of the data in the aggregation pipeline is cast.  Mongoose basically provides a more simplified API to the native mongo aggregation engine and users should be aware of this.  It's an advanced feature and as such should require an elevated understanding of how mongo really works.  In real mongo world, you have to cast ObjectIds (and other data) manually - I think the same should apply for aggregation so that the implementer can be in control of the performance.

**Comment by vkarpov15** [comment]
@DesignByOnyx's argument is one reason why this isn't supported. Another is that any implementation would be of limited use because the state of documents in the aggregation pipeline may not match any schema. Casting takes advantage of the fact that you know the path "user._id" should be an "_id", but after a "$project" or "$group" that may have changed. You could only really make this cast on `$match` pipeline stages that happen before any `$project` or `$group`.

As a workaround, you can create a document and then use the document's fields as parameters to aggregation. For instance, if you're doing something like:

```
MyModel.aggregate().match({ 'user._id': req.body.user });
```

You can always do

```
var m = new MyModel(req.body);
MyModel.aggregate().match({ 'user._id': m.user._id });
```

So the model constructor does casting for you
