### ISSUE TITLE
default values are not saved when added to existing documents

### ISSUE THREAD

**Issue by uptownhr** [LearnBoost/mongoose#2558]
If default values are added to your schema after a document has been created, updating your document without manually touching the property will result in the document being saved without the default value. 

Steps to reproduce
1. Create a test schema and save a few records
2. Update the test schema and add a default of Date.now
3. Write a script to pull a record. If you were to console.log this record, you'll actually see that the default is kicking in and the Date.now is populated
4. perform record.save( function(err,saved){ console.log(saved)}). Saved contains the default of Date.now. 
5. Check your db, and look for Date.now. You'll see that the property still does not exist. 

I think this is a pretty bad bug as it shows the property being populated before and after the record has been saved.

**Comment by vkarpov15** [comment]
Actually, this is expected behavior. You can't modify a schema after its already been compiled. In other words, if you create a model and then update the underlying schema, the changes to the underlying schema won't be reflected in the model. I [added some documentation](https://github.com/LearnBoost/mongoose/commit/ceaec5fe27eccba8d572048d3766d577d2adbccf) to make this more clear, but it hasn't hit the docs site yet.

**Comment by jondavidjohn** [comment]
I think you might be missing what the OP is pointing out.  I don't think he's talking about modifying the schema with the model or document in memory.

I think he's saying you

1. Create a Schema
2. Write a script that creates some of these. Script exits, data persists in the database.
3. Modify the Schema to add a new property (with a default)
4. Write a new script that pulls existing records under the newly modified schema.
5. See the new property (and default) that doesn't yet exist in the database record.
6. Call `.save()` but the new property (with the default value) is not saved to the database.

**Comment by jondavidjohn** [comment]
Example failling test

```javascript
  it('should mark populated defaults as modified when not a new document', function(done){
    var db = start();

    var Test = new Schema({
        original: String
    }, { collection: 'test' });

    var ModifiedTest = new Schema({
      original: String,
      another: {
        type: String,
        default: 'hello'
      }
    }, { collection: 'test' });

    var TestModel = db.model('TestModel', Test);
    var ModifiedTestModel = db.model('ModifiedTestModel', ModifiedTest);

    var test = new TestModel({original: 'original value'});

    test.save(function(err, savedTest) {
      ModifiedTestModel.findById(savedTest._id, function(err, modifiedTest) {
        assert.ifError(err);
        assert.equal(test.original, modifiedTest.original);
        assert.equal(modifiedTest.another, 'hello');
        assert.ok(modifiedTest.isModified('another'));
        done();
      });
    });
  })

```

**Comment by vkarpov15** [comment]
Hmm ok I see, that makes things a little more clear. My interpretation of the OP's issue was that he was modifying the schema after compiling the model, rather than using two separate models.

**Comment by vkarpov15** [comment]
So I put in a PR for this (#2750) that I'd like to sit on for a bit and think about, make sure it's sane. I'm going to put this into 4.0 though, because while it's probably not backwards breaking for anyone its still worth putting into release notes and a more significant behavior change than I'm comfortable putting into a patch.
