### ISSUE TITLE
Is there a need to worry about "." or "$"

### ISSUE THREAD

**Issue by crispen-smith** [LearnBoost/mongoose#2560]
Less an issue with functionality and more of a general query, around the characters . and $.   Both of these characters have semantic weight in Mongo and while it is probable that there is little risk with proper use of where(), or() etc. I am not 100% comfortable with blind string injection.

Is there any value in wrapping all string inputs with a regexp to unicode escape those characters?

**Comment by vkarpov15** [comment]
MongoDB is fundamentally different because SQL is a full language, whereas MongoDB's wire protocol is more declarative. I can't think of any cases where "$" and "." in values may cause problems - if you're querying with a user-specified regular expression then a malformed regex will probably cause an error, but that isn't something at the mongodb level.

**Comment by crispen-smith** [comment]
That makes perfect sense, thank you.
