### ISSUE TITLE
Why does __v not increment for modifications to non-arrays?

### ISSUE THREAD

**Issue by objectiveSee** [LearnBoost/mongoose#2563]
Mongoose will increment `__v` when an array is modified but not when a string or other non-array property is changed.  Does anybody have a link to or explanation of why it was decided to not increment `__v` for in this case?

**Comment by vkarpov15** [comment]
http://aaronheckmann.blogspot.com/2012/06/mongoose-v3-part-1-versioning.html

Basically versioning is enabled to mitigate the possibility of the most egregious race conditions, like the ones described in Aaron's post above. However, updating a single string outside of an array isn't quite as dangerous because there's no possibility that a race condition is causing you to update the wrong string. If you want to manually increment on every update of a certain field, that's pretty easy with custom setters and the `increment()` function, or if you want to increment every time the document changes you can add your own pre save hook that calls `increment()` if the document is dirty.
