### ISSUE TITLE
Can't overwrite an ObjectId field?

### ISSUE THREAD

**Issue by FREEZX** [LearnBoost/mongoose#2581]
Hi, i'm having an issue when trying to save a document.
I have the following code:

```javascript
exports.create = function(req, res) {
	var mapScreen = new MapScreen(req.body);
	console.log(req.user);
	mapScreen.user = req.user;
	console.log(mapScreen.user);

	mapScreen.save(function(err) {
		console.log(err);
		if (err) {
			return res.status(400).send({
				message: errorHandler.getErrorMessage(err)
			});
		} else {
			res.jsonp(mapScreen);
		}
	});
};
```
I try sending the following data:
```
{
	name: 'Map screen Name',
	toponymName: 'Map screen Name',
	user: { 
     		_id: '54ae6d7e1f30e25e35556775'
	},
	geonameId: 1234,
	location: {
		center: {
			coordinates: [22, 22]
		}
	}
}
```

This yields the following output:
```
{ _id: 54ae69d2c2241d7c338cfee0,
  random: [ 0.9119633759837598, 0.8231905356515199 ],
  name: 'Full',
  surname: 'Name',
  displayName: 'Full Name',
  email: 'test1@test.com',
  birthday: Thu Jan 08 2015 12:28:18 GMT+0100 (CET),
  sex: 'M',
  map: 54ae69d2c2241d7c338cfedf,
  __v: 0,
  __t: 'Person',
  connections_count: 0,
  data_filled: true,
  active: true,
  images: [],
  covers: [],
  roles: [ 'admin' ],
  cover_url: '',
  image_url: '',
  interests: [],
  occupations: [] }
54ae69d2c2241d7c338cfee0
{ [CastError: Cast to ObjectId failed for value "[object Object]" at path "user"]
  message: 'Cast to ObjectId failed for value "[object Object]" at path "user"',
  name: 'CastError',
  type: 'ObjectId',
  value: 
   { 
     _id: '54ae69d2c2241d7c338cfee0'
   },
  path: 'user' }
```

If, however, i omit the user object in the request body, the code runs without issue, successfully saving the object.

This leads me to believe that manually setting the user via ```mapScreen.user = req.user;``` has no effect IF the field was set in the object constructor.

I tried this with multiple versions including the stable and master version and the issue persists.
Is this a bug?

**Comment by vkarpov15** [comment]
So what does your schema look like? Is `user` an ObjectId or an object that contains an ObjectId in the schema?

**Comment by FREEZX** [comment]
It's a ObjectId that references Users

**Comment by vkarpov15** [comment]
So the error is because `req.body` contains user as an object rather than an ObjectId. Try sending `{ user: '54ae69d2c2241d7c338cfee0' }` in the body instead

**Comment by FREEZX** [comment]
maybe, but shouldn't ```mapScreen.user = req.user;``` overwrite it, thus removing the error on save?

**Comment by FREEZX** [comment]
And i think the row with ```54ae69d2c2241d7c338cfee0``` indicates that the value is correct before save gets called

**Comment by vkarpov15** [comment]
Well `req.user` is also an object with an `_id` field as opposed to an actual ObjectId.

**Comment by FREEZX** [comment]
True, but i also tried ```mapscreen.user = req.user._id``` with the same results.

**Comment by vkarpov15** [comment]
So looking at it more closely, looks like this only happens for refs. If you don't specify `ref` in the schema, this issue doesn't happen. I'll investigate more closely now.

**Comment by vkarpov15** [comment]
So part of the issue is that setting `mapscreen.user = req.user` won't fix the underlying castError. The original `new MapScreen(req.body);` call will cause the doc to have a castError that you can't get rid off without doing a reset on the whole doc. So basically, if the original data was malformed, mongoose won't let you save the doc even if you fix the error. That's a very fundamental limitation that's hopefully going to go soon, but will still be here for the next few months.

However, the fact that the original `new MapScreen(req.body);` call was creating a cast error is a limitation that's pretty easy to fix. Mongoose is smart enough to check if the object has an `_id` field and if the `_id` field is an ObjectId, but not smart enough to check if its a valid ObjectId hex string. I added that ability and it'll be released with 4.0.0. Won't be backported to 3.8.x though because its potentially backwards breaking.

**Comment by samirfares** [comment]
Hi, is this issue fixed on 4.x.x version? I am using 3.8.30, Is there any way to workarround on this?
Thank you.

**Comment by vkarpov15** [comment]
1) yes
2) don't rely on mongoose 3.8 to cast an object with `_id` to an ObjectId.
