### ISSUE TITLE
Model.aggregate(..).read('secondary') does not return an error if no secondary nodes available

### ISSUE THREAD

**Issue by cblanc** [LearnBoost/mongoose#2606]
I'm running a single node replica (version 2.6.4) set in my development setup using Mongoose version 3.8.20.

My `aggregate` queries look something like this:

```
MyModel.aggregate({
	$match: {
		createdAt: {
			$gte: start,
			$lte: end
		}
	}
}, {
	$group: {
		_id: { day: {$dayOfMonth: "$createdAt"}, month: {$month: "$createdAt"}, year: {$year: "$createdAt"} },
		count: {$sum: 1}
	}	
})
.read("secondary")
.exec(callback);
```

Ordinarily my read preference is set to "secondaryPreferred" because I'm running a single node for testing and development while there's a replica set in production. However I swapped read preference to "secondary" just to reassure myself that my query was sensitive to `read()` and contrary to what I expected, the query ran just fine. I did not receive any error to my callback.

According to the documentation for `Query#read`, querying with secondary should return an error if no secondaries are available. Is the behaviour for `Aggregate#read` meant to differ? 

Additional Info:
- My schema read preference is left as default ("primary") - changing it does not make a difference
- The query runs fine with using any setting: E.g. nearest, primaryPreferred, etc
- The query fails as expected if I pass `read` some random string

**Comment by vkarpov15** [comment]
So this may be a "works as expected" depending on how you're connecting, but pointed out a bug in mongoose anyway :)

The reason why you are not getting an error is because, unless you specify multiple hosts or the `replicaSet` option, [mongodb drivers will assume you are connecting to a standalone instance](http://docs.mongodb.org/manual/reference/connection-string/#uri.replicaSet). Since mongoose thinks you're connected to a standalone, it will not hit any of the read preference code by design.

Unfortunately, it looks like mongoose doesn't actually conform to the docs in terms of checking for a `replicaSet` parameter in the connection uri. Mongoose will open up a repl set if and only if you specify multiple hosts. I'll fix this asap, so you can open repl set connections using `createConnection('mongodb://hostname:27000/test?replicaSet=myRsName')`.

In the meantime, you can work around this by using:

```
mongoose.connection.openSet('mongodb://hostname:27000/test');
```

Instead of 

```
mongoose.connect('mongodb://hostname:27000/test');
```

That will explicitly tell mongoose to open a connection to a replica set.

**Comment by cblanc** [comment]
Thanks very much for the information. Much appreciated.
