### ISSUE TITLE
allow null in Date arrays

### ISSUE THREAD

**Issue by reezer** [LearnBoost/mongoose#2661]
The problem described in #840 appears to happen with Date Arrays aswell.

**Comment by vkarpov15** [comment]
Actually, this is not an issue. `[1,,2]` is not a valid number array currently, because:

```
$ node
> var x = [1,,2];
undefined
> x[1]
undefined
> typeof x[1]
'undefined'
> x
[ 1, , 2 ]
> 
```

Mongoose allows `[1, null, 2]` but not `[1,,2]` or `[1, undefined, 2]`. Same holds true for dates - `[new Date('2011-06-01T00:00:00.000Z'), null, Date.now()]` is valid, `[new Date('2011-06-01T00:00:00.000Z'),, Date.now()]` is not. The fact that undefined is not a valid array value is a much more fundamental assumption in mongoose, and IMO its correct. Do you think that assumption is wrong?
