### ISSUE TITLE
Dropped database doesn't re-ensureIndexes

### ISSUE THREAD

**Issue by bevacqua** [LearnBoost/mongoose#2671]
Use case: each integration test connects to a database, drops it, uses the connection, and disconnects.

Expectation: `.ensureIndex` gets called just like at startup, if necessary.

**Comment by vkarpov15** [comment]
Hmm you're going to have to explain this to me. When you create a new Model, it should run ensureIndexes() by default, no?

**Comment by bevacqua** [comment]
Yes. Whenever a test runs (each test of hundreds), I establish a database connection, then I do `mongoose.connection.db.dropDatabase(done)`, and run my tests. The problem is that dropping the database destroys the collections `mongoose` automatically created, and when the next test comes along, `mongoose` re-creates the collections where needed, but it doesn't run `ensureIndex` again

**Comment by vkarpov15** [comment]
This isn't really something that mongoose can do well right now. We don't have a dropDatabase() helper, so we don't really know when you've dropped a db, and asking the db "do these indexes exist?" on every query would be abysmally slow. The reason why the collections are recreated is that the mongodb server does it for you: when you try to write to a collection that doesn't exist, mongodb creates the collection.

There are a couple really simple workarounds:

1) You can just call `Model.ensureIndexes()` yourself, such as in your `beforeEach()` hook if you're using mocha.

2) You can destroy your models after each test and then recreate them.

3) Instead of running `dropDatabase()`, you can just run a `remove()` on each individual model: `MyModel.remove({}, function(err) {}};`. This will remove all the data but leave the indexes intact.

This would also be a case where somebody could write a nice mongoose plugin :)
