### ISSUE TITLE
Mongoose Kue

### ISSUE THREAD

**Issue by knutole** [LearnBoost/mongoose#2695]
Hi. I have an issue with concurrent writes to `db`, as MongoDB only allows one write at a time. Considering putting up a Kue to deal with this - then realised you guys at LearnBoost are behind both projects!? 

So wondering if you have any good solutions to queuing writes to MongoDB, or if setting up a Kue is the best way?

Thanks

**Comment by vkarpov15** [comment]
MongoDB doesn't allow only one write at a time. In 2.6 it's one write per database at a time, which can be a bit difference depending on your use case. Also, why do you need to put a queueing solution in front of MongoDB? The mongodb server won't drop incoming writes just because they have to wait on a lock.

**Comment by knutole** [comment]
Hi, thanks for your feedback. I have had some issues with `locking` before, although I don't have the exact error-message here. I'll investigate.

**Comment by vkarpov15** [comment]
Also, sad news, but LearnBoost no longer really exists as an independent company. They pivoted to become CloudUp and subsequently got bought by Automattic. I actually work at MongoDB, have never worked for LearnBoost or related companies :)

Let me know if you find any more information related to your locking issues.
