### ISSUE TITLE
Possibility to persist virtual setter/getter to MongoDB when using bulk insert?

### ISSUE THREAD

**Issue by nottinhill** [LearnBoost/mongoose#2713]
I have my domain logic defined in virtuals, such as:

https://gist.github.com/nottinhill/78565d04bc01278de3a5#file-gistfile1-js

I have quite a few complex virtual getters. In order to minimise refactoring and maximise re-usability for different data sets I would like to persist the data returned by my virtuals getters to my MongoDB. 

From my understanding I can achieve this with virtual setters. This is a overview of my current code:

1.) Parse Data (big data)
2.) Use Bulk Insert without Mongoose Schema due to this bug: http://stackoverflow.com/questions/24466366/mongoose-rangeerror-maximum-call-stack-size-exceeded
3.) Query Data with virtual getters

Due to the bulk insert bug I guess using virtual setters when using MongoDB Native Driver is not possible? 

Would it be possible to add an additional step 4.) in order to load the populated model via the virtual getters into node.js and then bulk insert the populated data back into MongoDB to persist the population?

**Comment by vkarpov15** [comment]
No, the whole point of virtuals is that [they are not persisted to mongodb ever, as the first line of the docs says](http://mongoosejs.com/docs/guide.html#virtuals). If you really want to make it so all of your virtuals are stored in the database rather than computed when accessed, something like this would be the ideal way. Just make sure you remove all of your virtuals from your schema definition afterwards, otherwise they would conflict with the real path names.

```javascript
var stream = MyModel.find({}).stream();
var docsLoaded = 0;
var docsSaved = 0;
var done = false;
stream.on('data', function(doc) {
  var updated = doc.toObject({ virtuals: true });
  ++docsLoaded;
  MyModel.update({ _id: doc._id }, updated, { overwrite: true }, function(err) {
    if (done && ++docsSaved >= docsLoaded) {
      process.exit(0);
    }
  });
});

stream.on('end', function() {
  done = true;
});
```
