### ISSUE TITLE
Default values for arrays irregular 

### ISSUE THREAD

**Issue by gmaniac** [LearnBoost/mongoose#2734]
"mongoose": "^3.8.23"

Depending on how you are declaring an array it will use the default or not. I guess this is more informational than an issue, I might even be doing this incorrectly (if so please let me know).

If you declare an array this way with a default it will not use the default:

    roles:  [{ type: String, required: true, enum: ['aquaman', 'flash', 'superman', 'developer'], default: 'aquaman' }]

you will get `roles: []`

If you do it this way it will use your default value.

    roles:  { type: [String], required: true, enum: ['aquaman', 'flash', 'superman', 'developer'], default: 'aquaman' }

I am assuming because it is an array it thinks it has a value and does not use the default.

Thanks!

**Comment by vkarpov15** [comment]
Expected behavior. Mongoose will try to cast the default value to whatever type you specified, so in your case it will cast it to an array that contains one string, 'aquaman'. However, in the second case your `enum` validator will not work. `enum` is not a built-in validator for arrays, only strings.
