### ISSUE TITLE
Error: Can't use $eq with ObjectId.

### ISSUE THREAD

**Issue by CTAPbIuMABP** [LearnBoost/mongoose#2752]
why?

$ne works just fine

**Comment by vkarpov15** [comment]
Can you provide me an example of what you're trying to do? I don't quite understand.

Also, be careful with using `$eq`, it isn't [formally supported unless you're using mongodb server >= 3.0.0](http://docs.mongodb.org/manual/reference/operator/query/eq/)

**Comment by CTAPbIuMABP** [comment]
oh i c
i'm using 2.6.8
```js
User.find({
	_id: {$eq: new mongoose.Types.ObjectId()}
})
```
but shouldn't it throw kind of mongo error `$eq is not supported` because `Can't use $eq with ObjectId` i can use it with something else

**Comment by vkarpov15** [comment]
The fact that it throws an error is worrisome, I'll look into that. But otherwise, unless you're using mongodb server >= 3.0, $eq is not a supported operator so this is a non-issue. If you're worried about security implications, see [my article on query selector injection attacks](http://thecodebarbarian.com/2014/09/04/defending-against-query-selector-injection-attacks). Unless you're explicitly trying to defend against QSI (querying with user-provided data that may be an object) `$eq` is probably redundant

**Comment by CTAPbIuMABP** [comment]
thx

**Comment by vkarpov15** [comment]
I'll re-open for now because I want to make sure mongoose doesn't blow up when $eq is used, because it is a valid query selector in 3.0 and mongoose should support it

**Comment by johnantoni** [comment]
still a problem here.

    Classroom.find({ 'user': id, 'archived': {$eq: true} })

fails but

    Classroom.find({ 'user': id, 'archived': {$ne: false} })

Using mongoose 5.0.10

Anyone else having the same issue?
