### ISSUE TITLE
4RC3 findOneAndUpdate returns not updated doc

### ISSUE THREAD

**Issue by whitecolor** [LearnBoost/mongoose#2756]
In 4rc3 `findOneAndUpdate` works incorrectly (it updates, but callback result is not updated version of document). 

```javascript
var childSchema = new Schema({ 
    name: String,        
});

var child = new Child({ name: 'Mary'});

child.save(function(){
    Child.findOneAndUpdate({_id: child.id}, {name: 'Jery}, function(err, updated){
        console.log('updated.name', updated.name) // --> 'Mary' - value before update
        Child.findOne({_id: child.id}, function(err, found){
            console.log('found.name', found.name) // --> 'Jerry' - value was actually updated in DB
        })
    })
})
```

**Comment by vkarpov15** [comment]
This is by design. See [4.0 release notes](https://github.com/LearnBoost/mongoose/wiki/4.0-Release-Notes#backwards-breaking-changes) and #2262. MongoDB's [findAndModify](http://docs.mongodb.org/manual/reference/command/findAndModify/#definition) has a `new` option that determines whether it returns the document before or after update. In the mongodb server and node driver `new` is false by default, but in mongoose 3.x `new` was true by default. In 4.0 mongoose will use false by default because IMO mongoose shouldn't set conflicting defaults unless there's a very good reason to.

```javascript
var childSchema = new Schema({ 
    name: String,        
});

var child = new Child({ name: 'Mary'});

child.save(function(){
    // Added the 'options' parameter below, setting the `new` option to true to get the new doc back
    Child.findOneAndUpdate({_id: child.id}, {name: 'Jery}, { 'new': true }, function(err, updated){
        console.log('updated.name', updated.name) // --> 'Mary' - value before update
        Child.findOne({_id: child.id}, function(err, found){
            console.log('found.name', found.name) // --> 'Jerry' - value was actually updated in DB
        })
    })
})
```

**Comment by whitecolor** [comment]
Thanks.

**Comment by flaurian** [comment]
Putting the default to false really is one of those bad good ideas. 
Thanks for the time wasted changing that during the version migration.

**Comment by vkarpov15** [comment]
Sorry for difficulty. It's up there on the migration docs. However, this was a necessary change IMO.
